### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by samuelpatro** [ts95/lang-detector#2]
Hey, i getting this error when i want to compile project, i using Nuxtjs

```
ERROR in vendor.bundle.4121f31b99921401b12c.js from UglifyJs
Unexpected token name «of», expected punc «;» [./node_modules/lang-detector/index.js:399,0][vendor.bundle.4121f31b99921401b12c.js:36331,18]
```

**Comment by hosein2398** [comment]
Use this fork and see if you still get same error or not:
[https://github.com/hosein2398/lang-detector](https://github.com/hosein2398/lang-detector)

**Comment by samuelpatro** [comment]
@hosein2398 looks like working

**Comment by samuelpatro** [comment]
@hosein2398 
After testing it more there is error: `TypeError: statistics.push is not a function` its on this line

```
statistics.push([ results[result].language , results[result].points]);
```

**Comment by hosein2398** [comment]
@Samuell1  
I will try to check in days, thanks for reporting .
Glad that fork did the job for you.

**Comment by samuelpatro** [comment]
@hosein2398 yeah with disabled statistics its working fine

**Comment by hosein2398** [comment]
This error `TypeError: statistics.push is not a function ` happens in my fork or in main repo?
"With disabled statistics works fine" you mean in my fork or in main repo ?

**Comment by samuelpatro** [comment]
@hosein2398 your repo
